/*
Copyright 2021 ChainSafe Systems
SPDX-License-Identifier: LGPL-3.0-only
*/
name: React.TS install, lint, build, License

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.4.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, lint, build
        run: |
          yarn install --frozen-lockfile
          yarn run lint
          yarn run license-check
          yarn run build --if-present
          # yarn test
        env:
          CI: true
