name: React.TS

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04

    strategy:
      matrix:
        node-version: [14.4.0]

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ matrix.node-version }}
      - name: yarn install, build, lint and test
        run: |
          yarn install --frozen-lockfile
          yarn run lint
          yarn run build --if-present
          # yarn test
        env:
          CI: true
