name: License

on:
  pull_request:
    types: [opened, synchronize, reopened]

jobs:
  license:
    name: License Check
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: License Check
        run: make license-check
